### ISSUE TITLE
Build failures on Lunar

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-gbp/cartographer_ros-release#4]
Looks like the [last release](https://github.com/ros/rosdistro/pull/17312) with the [Gmock CMake patch](https://github.com/ros-gbp/cartographer-release/pull/5) fixed the CMake issue. It successfully built on [ubuntu xenial for lunar](http://build.ros.org/view/Queue/job/Lbin_uX64__cartographer_ros__ubuntu_xenial_amd64__binary/5/console):
- Though the tests were not ran for some reason:

```
00:09:42.012 The following tests FAILED:
00:09:42.012 	  1 - _ctest_cartographer_ros_gtest_time_conversion_test (Failed)
00:09:42.012 	  2 - _ctest_cartographer_ros_gtest_configuration_files_test (Failed)
00:09:42.012 	  3 - _ctest_cartographer_ros_gtest_msg_conversion_test (Failed)
00:09:42.012 	  4 - _ctest_cartographer_ros_gtest_occupancy_grid_test (Failed)
```

If [fails to link](http://build.ros.org/job/Lbin_ds_dS64__cartographer_ros__debian_stretch_amd64__binary/3) on Debian, I think we're hitting https://github.com/ros-perception/perception_pcl/issues/139. We'll likely need to patch CMake and package.xml to fix it (either the ugly way by injecting new depndency (https://github.com/ros-planning/navigation/pull/578/files), or by removing the targets causing the issues if we don't use them (https://github.com/ros-perception/perception_pcl/pull/151/files))

@k-okada @7675t FYI

**Comment by mikaelarguedas** [comment]
Attempt to fix Lunar builds:
https://github.com/ros-gbp/cartographer-release/pull/6
https://github.com/ros-gbp/cartographer_ros-release/pull/5

Release:
https://github.com/ros/rosdistro/pull/17315
https://github.com/ros/rosdistro/pull/17316

**Comment by k-okada** [comment]
@mikaelarguedas thank you for fix!

**Comment by mikaelarguedas** [comment]
closing this as all build issues appear to have been resolved (tests are still not ran but catkin packages usually don't run any tests on binary jobs so I guess that's fine).

@k-okada @7675t if you get a chance to try the packages, that will be much appreciated. They are currently in the [shadow repository](http://wiki.ros.org/ShadowRepository), and will be in main after [tomorrow's sync](https://discourse.ros.org/t/preparing-for-lunar-sync-2018-04-02/4372). Once confirmed to be working properly on Lunar we can release them into kinetic.

Thanks !

**Comment by 7675t** [comment]
Yeah, I confirmed it can produce maps for [demos](https://google-cartographer-ros.readthedocs.io/en/latest/demos.html) and [my robot](https://github.com/tork-a/roomblock/tree/cartographer_020/roomblock_mapping), using shadow-fixed lunar packages.
Thank you! @mikaelarguedas

**Comment by k-okada** [comment]
Since `cartographer` is already released on kinetic and that's incldues @mikaelarguedas 's fix (https://github.com/ros-gbp/cartographer-release/pull/6) https://github.com/ros-gbp/cartographer-release/blob/debian/ros-kinetic-cartographer_0.2.0-2_xenial/cmake/functions.cmake#L75
@7675t I think we're ready to release on kinetic. Could you try that? when bloom ask you for `version`, type '0.2.0'
```
What version are you releasing (version should normally be MAJOR.MINOR.PATCH)? 0.2.0

```

**Comment by 7675t** [comment]
@k-okada 
OK, I've done. Let's see.

**Comment by mikaelarguedas** [comment]
Thanks @7675t :+1:

**Comment by k-okada** [comment]
it seems working ->
http://repositories.ros.org/status_page/ros_kinetic_default.html?q=cartographer
thanks!

--
◉ Kei Okada


2018-04-26 23:29 GMT+09:00 Mikael Arguedas <notifications@github.com>:
